import express, { Application } from 'express';
import { json } from 'body-parser';
import dotenv from 'dotenv';
import routes from './startup/routes';
import { catchError } from './middleware/catchErrorMiddlerware';
const app: Application = express();
dotenv.config({ path: '.env' });
app.use(json());
routes(app);
app.use(catchError);
export default app;
